homeassistant:
  name: Home

  ## TODO: move to secrets
  # Location required to calculate the time the sun rises and sets
  latitude: 51.169241
  longitude: 0.630123
  elevation: 24
  
  unit_system: metric
  time_zone: Europe/London

  packages: !include_dir_named packages

energy:
my:
mobile_app:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# modbus: !include modbus.yaml
template: !include_dir_merge_list template
lovelace: !include lovelace.yaml
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.23.211

# Database
recorder:
  db_url: !secret psql_string